name: cyclegan
channels:
    - menpo
    - soumith
dependencies:
    - python==3.6
    - pytorch==0.2.0
    - opencv3=3.1.0
    - numpy==1.13.1
    - scipy==1.0.0
    - pip:
        - stl==0.0.3
        - gym==0.9.2
        - tensorflow
        - ipdb==0.10.3
        - tblib==1.3.2
        - Pillow==4.2.1
        - PyOpenGL==3.1.0
        - click==6.7
        - python-dateutil==2.6.1
        - pyyaml==3.12
        - easydict==1.7
        - boto3==1.4.4
        - mako==1.0.7
        - redis==2.10.5
        - Flask==0.12.2
        - cupy==1.0.1; 'linux' in sys_platform
        - cached-property==1.3.0
        - matplotlib==2.0.0
        - dominate==2.3.1
        - visdom==0.1.6.1

